import os
import shutil
import click

cwd = os.getcwd()

@click.group()
def cli():
    """Blended: Static Website Generator"""

@cli.command('init', short_help='Initiate a new website')
def init():
    """Initiates a new website"""
    print("Blended: Static Website Generator -\n")
    wname = raw_input("Website Name: ")
    wdesc = raw_input("Website Description: ")
    wlic = raw_input("Website License: ")
    aname = raw_input("Author(s) Name(s): ")

    templ_dir = os.path.join(cwd, "templates")
    if not os.path.exists(templ_dir):
        os.makedirs(templ_dir)

    cont_dir = os.path.join(cwd, "content")
    if not os.path.exists(cont_dir):
        os.makedirs(cont_dir)

    build_dir = os.path.join(cwd, "build")
    if not os.path.exists(build_dir):
        os.makedirs(build_dir)
    
    conf_file_dir = os.path.join(cwd, "conf.py")
    conf_file = open(conf_file_dir, "w")
    conf_file.write('# Configuration is atuomatically generated by Blended, feel free to edit any values\n\n')
    conf_file.write('website_name = "'+wname+'"\n')
    conf_file.write('website_description = "'+wdesc+'"\n')
    conf_file.write('website_license = "'+wlic+'"\n')
    conf_file.write('author_name = "'+aname+'"\n')
    conf_file.write('\n')
    conf_file.close()
    
    print("\nThe required files for your website have been generated.")

@cli.command('purge', short_help='Purge the Blended files')
def purge():
    """Initiates a new website"""
    print("Purging the Blended files!")

    templ_dir = os.path.join(cwd, "templates")
    shutil.rmtree(templ_dir)

    cont_dir = os.path.join(cwd, "content")
    shutil.rmtree(cont_dir)

    build_dir = os.path.join(cwd, "build")
    shutil.rmtree(build_dir)
    
    conf_file_dir = os.path.join(cwd, "conf.py")
    os.remove(conf_file_dir)

if __name__ == '__main__':
    cli()
