import os
import shutil
from shutil import copyfile
import sys

def check_config():
    """If the config.py file exists, back it up"""
    config_file_dir = os.path.join(cwd, "config.py")
    if os.path.exists(config_file_dir):
        print("Making a backup of your config file!")
        config_file_dir2 = os.path.join(cwd, "config.py.oldbak")
        copyfile(config_file_dir, config_file_dir2)

def create_config(app_version=6.0, site_title=""):
    """Generates a config file from the information"""
    config_file_dir = os.path.join(cwd, "config.py")

    config_file = open(config_file_dir, "w")
    config_file.write('blended_version = ' + app_version + '\n')
    config_file.write('\n')
    config_file.write(
        '# Configuration is automatically generated by Blended (http://jmroper.com/blended), feel free to edit any values below')
    config_file.write('\n')
    config_file.write('website_name = "' + wname + '"\n')
    config_file.write('website_description = "' + wdesc + '"\n')
    config_file.write(
        'website_description_long = "' + wdescl + '"\n')
    config_file.write('website_license = "' + wlic + '"\n')
    config_file.write('website_language = "' + wlan + '"\n')
    config_file.write('website_url = "' + wurl + '"\n')
    config_file.write('\n')
    config_file.write('author_name = "' + aname + '"\n')
    config_file.write('author_bio = "' + abio + '"\n')
    config_file.write('\n')
    config_file.write('home_page_list = True\n')
    config_file.write('\n')
    config_file.write('plugins = [] # Place all needed plugins in here\n')
    config_file.write(
        'custom_variables = {} # Place all custom variables in here\n')
    config_file.write('\n')
    config_file.write('minify_css = False\n')
    config_file.write('minify_js = False\n')
    config_file.write('\n')
    config_file.write('# The following values are used for FTP uploads')
    config_file.write('\n')
    config_file.write('ftp_server = "localhost"\n')
    config_file.write('ftp_username = "user"\n')
    config_file.write('ftp_password = "pass"\n')
    config_file.write('ftp_port = 21\n')
    config_file.write('ftp_upload_path = "public_html/myWebsite"\n')
    config_file.close()
