"""This holds the site init code"""
import os
import shutil
from shutil import copyfile
import sys
from functions import create_folder

# Very important, get the directory that the user wants to run commands in
cwd = os.getcwd()


def check_config():
    """If the config.py file exists, back it up"""
    config_file_dir = os.path.join(cwd, "config.py")
    if os.path.exists(config_file_dir):
        print("Making a backup of your config file!")
        config_file_dir2 = os.path.join(cwd, "config.py.oldbak")
        copyfile(config_file_dir, config_file_dir2)


def create_config(app_version=6.0, site_title="", site_tagline=""):
    """Generates a config file from the information"""
    config_file_dir = os.path.join(cwd, "config.py")

    with open(config_file_dir, "w") as config_file:
        config_file.write('blended_version = ' + app_version + '\n')
        config_file.write('\n')
        config_file.write(
            '# Configuration is automatically generated by Blended (http://jmroper.com/blended), feel free to edit any values below.\n')
        config_file.write('site_title = "' + site_title + '"\n')
        config_file.write('site_tagline = "' + site_tagline +
                          '" # In a few words, explain what this site is about.\n')
        config_file.write('site_language = "en-US"\n')
        config_file.write('\n')
        config_file.write('date_format = "F j, Y"\n')
        config_file.write('time_format = "g:i a"\n')
        config_file.write('permalink_format = "day_and_name"\n')
        config_file.write('\n')
        config_file.write('blog_list_posts = 10\n')
        config_file.write('blog_list_post_item = "full_text"\n')
        config_file.write('front_page = "latest_posts"\n')
        config_file.write('\n')
        config_file.write('theme = "basic"\n')
        config_file.write('plugins = []\n')
        config_file.close()


def generate_required_folders():
    """Creates the standard folders for a Blended website"""
    create_folder(os.path.join(cwd, "content")
    create_folder(os.path.join(cwd, "content", "pages"))
    create_folder(os.path.join(cwd, "content", "posts"))

    create_folder(os.path.join(cwd, "includes"))
    create_folder(os.path.join(cwd, "includes", "authors"))
    create_folder(os.path.join(cwd, "includes", "plugins"))
    create_folder(os.path.join(cwd, "includes", "themes"))
    create_folder(os.path.join(cwd, "includes", "media"))
